# Generated by Django 6.0.2 on 2026-03-31 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodge', '0003_booking_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to='gallery/')),
            ],
        ),
    ]
