# Generated by Django 6.0.2 on 2026-04-01 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodge', '0007_delete_gallery_booking_booking_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
